import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import StoreProvider from "./StoreProvider";
import { ToastContainer } from "react-toastify";
require("dotenv").config()

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Authentication App",
  description: "Generated by AJS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-400`}
      >
        <Navbar/>
        <StoreProvider>
        {children}
        <ToastContainer />
        </StoreProvider>
      </body>
    </html>
  );
}
